// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExitError is an autogenerated mock type for the ExitError type
type ExitError struct {
	mock.Mock
}

// Error provides a mock function with given fields:
func (_m *ExitError) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ExitStatus provides a mock function with given fields:
func (_m *ExitError) ExitStatus() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExitStatus")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Exited provides a mock function with given fields:
func (_m *ExitError) Exited() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Exited")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// String provides a mock function with given fields:
func (_m *ExitError) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewExitError creates a new instance of ExitError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExitError(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExitError {
	mock := &ExitError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
